# Generated by Django 3.2.13 on 2022-04-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0002_rename_request_borrowrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_response', to='request.borrowrequest')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_responder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
