# Generated by Django 3.2.13 on 2022-04-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_borrowresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowresponse',
            name='borrow_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_responses', to='request.borrowrequest'),
        ),
    ]
