# Generated by Django 3.2.13 on 2022-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_borrowresponse_borrow_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='accepted_response',
            field=models.BooleanField(default=False),
        ),
    ]
